
---
- hosts: server2
  gather_facts: no
  become: true
  become_method: su
  vars:
    var1: Contenido-Variable-var1
    nodos: ['nodo1','nodo2']
    _labelAtoms: ["papythclb01","panodeclb01","panetcclb01","pajavaclb02","pajavaclb01","pagentclb03","pagentclb01","paansiclb01","idseopclb02","idseopclb01"]
    _versionCasc: 1
    _versionDesc: "Namespaces xxxxx"
    _namespace: "actm-autocontrolm-qas adpc-admpreycomision-qas almc-integrations-qas apdk-appdkuextension-qas    apdm-appdmachine-qas aple-apislending-qas arqa-arquitectura-qas arqv-msarqventas-qas auth-authcanales-qas   bfft-tasi-qas cdsa-solanaliticas-qas cnet-crossnetcore-qas crnj-crossnodejs-qas ctqs-teraapirestnet-qas    devo-devops-qas dwos-dataanalytics-qas eqrm-echeq-qas gara-portalgarantias-qas gdms-gddigital-qas   gres-grecosystem-qas ierm-sie-qas incc-comcustodia-qas inml-orquestadordocs-qas inpq-infopaquetes-qas    isop-antecedentes-qas jaut-autenticacion-qas limk-marketplace-qas lsgo-sitioleasing-qas   mobi-galiciamobile-qas nbrm-nuevobalance-qas nvsm-sincpersonas-qas obad-tarjetasonb-qas obaf-perfil-qas    obag-inversiones-qas obah-transferencias-qas obal-financioonba-qas"
    _server: "https://ocp-stg.bancogalicia.com.ar"
  tasks:
    - debug: msg='var1 {{ var1 }}'
################################################

    - name: armado de bundle
      template:
        src: bundle/bundle.yml.j2
        dest: /tmp/bundle.yml
################################################
    - name: armado de jenkins
      template:
        src: jenkins/jenkins.yml.j2
        dest: /tmp/jenkins.yml
################################################
    - name: armado de Plugins
      template:
        src: plugins/plugins.yml.j2
        dest: /tmp/plugins.yml
################################################
    - name: armado de Plugins-catalog
      template:
        src: plugins-catalog/plugins-catalog.yml.j2
        dest: /tmp/plugins-catalog.yml
 