---
- hosts: ljenkiclb02
  vars:
       git_version: "2.30.0"
  tasks:
    - name: Download GIT de nexus banco galicia
      get_url:
        url: http://nexus.bancogalicia.com.ar/repository/alm/git/git-{{git_version}}.tar.gz
        dest: /tmp/git-2.30.0.tar.gz
        checksum: sha256:8db4edd1a0a74ebf4b78aed3f9e25c8f2a7db3c00b1aaee94d1e9834fae24e61
