---
- name: baja-servico-cloudbees.yml
  hosts:  "{{ variable_host | default('labnexus') }}"
  become: true
  become_method: su
  gather_facts: false
  tasks:
    - name: "{{ ansible_play_name}} : bajar servicio Master"
      service: name=cloudbees-core-cm state=stopped 
